### ISSUE TITLE
How we talk about the community?

### ISSUE THREAD

**Issue by stecaron** [dot-layer/community-tasks#13]
Let's try to define a way to talk about the community at large ! Shoot your ideas in that issue and let's have discussions. 

Personally, I think it would be at least a good idea to make some posts on social networks ! We have some pictures of the chalet that we can use also !

**Comment by samperochkin** [comment]
À propos du meetup qui vient, j'aime l'idée d'avoir de quoi qui rend ça visible, mais je sais pas si ça a besoin d'être très visible... Comment je vois ça c'est qqchose qui est visible pour la personne avec qui tu parles directement, comme un gros point (dot) noir sur le dessu de la main mettons... C'est quelques choses qui va pousser les gens intéressés à poser des questions, mais ça sous-entend qu'on fasse un effort pour parler au maximum de gens...

Un genre de pin qu'on installerait sur nos chandail serait p-e pas pire aussi. Dans tous les cas je pense qu'on devrait se donner comme mission de parler à tout le monde...

**Comment by samperochkin** [comment]
Si je comprends bien, tu as l'intention de (au moins brièvement) parler de .layer en introduisant la problématique (ou aller chercher les données etc etc). Si tu pouvais, en faisant ça, décrire la communauté (en une ou deux phrases) et nommer les layeriens présent à l'événement et les pointer + dire ce qui nous identifie, ce serait pas pire. Ensuite ce serait de notre ressort de se promener pour parler aux gens pour leur donner la chance de poser des questions si jamais.

Mais comme tu disais, si on peut avoir de quoi de voyant, c'est certain que ça nuirait pas.

**Comment by stecaron** [comment]
Ouais mon plan c'était vraiment de dire une phrase ou deux en faisant l'annonce du workshop a Nic et du hackathon le samedi. Un ptit mot vraiment quick en parlant du fait que les repos se retrouvent sur une organisation qui s'appelle "dot-layer". Après ca j'aurais juste dis que plusieurs d'entres eux sont présents ce soir et que vous pouvez les distinguer par un "lolk" écrit sur le bras, genre vous pouvez aussi leur poser des questions si vous etes curieux bla bla bla ...

**Comment by stecaron** [comment]
"Se réunir est un début, rester ensemble est un progrès, travailler ensemble est la réussite" (Henry Ford)

**Comment by stecaron** [comment]
Close for now. We'll have a better idea in coupls of months.
