### ISSUE TITLE
SSC award: promoting statistics and probability

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/community-tasks#14]
Voici ledit e-mail:

This is a new call for proposals for advancing the goals of the SSC  to promote statistics and probability to students and educators, or to help students and young researchers develop careers in the statistical sciences. 
The SSC Board will award between $500 and $5,000 for the best proposals received by January 31, 2019.  Preference will be given to proposals that have a broad reach, e.g. are regional or national rather than local, and that are able to obtain additional support.  The number of awards will depend on the funds available.  If a proposal involves electronic services, proposers are encouraged to contact the Electronic Services Manager of the SSC for advice.
In your proposal, please provide:
   - Your idea and a rationale, explaining how it fits with the mission of the SSC
   - Who will implement the project and how it will be implemented
   - If the project involves website design, where the site will be hosted
   - A detailed timeline for the use of the funds
   - Who will be responsible for administering and reporting on the project 
   - A detailed budget with justification. 

Also, please comment on the timeframe of the project and any ongoing costs that might arise.  
Send your proposal by January 31, 2019 to Mary Thompson, Chair of the SSC Fundraising Committee, at methomps@uwaterloo.ca

**Comment by samperochkin** [comment]
On peut drop la convé e-mail et faire ça ici pour que ce soit plus transparent. (Juste la communauté voit ça right?)

**Comment by davebulaval** [comment]
@caronl @jplecavalier @chblw @jtbai Gros potentiel.

**Comment by stecaron** [comment]
Un [repo](https://github.com/dot-layer/SSC-proposal) a été créé pour cela.
