### ISSUE TITLE
Site web bilingue

### ISSUE THREAD

**Issue by stecaron** [dot-layer/community-tasks#16]
ETA: 18 Janvier 2019

**Comment by stecaron** [comment]
Reste vraiment pas grand chose gailles ... j'aimerais ca qu'on merge ça au PC. Reste juste à valider la traduction du "About" et regler le inline code du sidebar.

**Comment by samperochkin** [comment]
J'ai fait quelques modifs aux about (en et fr)

**Comment by stecaron** [comment]
Il resterait juste à voir ce qu'on fait avec le inline code du `Hello World!` dans le sidebar @chblw.
