### ISSUE TITLE
Commande t-shirt .Layer

### ISSUE THREAD

**Issue by stecaron** [dot-layer/community-tasks#23]
ETA: 15 Février 2019 (envoyer la commande)

**Comment by jcyelle** [comment]
Pour les grandeurs on fait quoi? On pourrait faire un sondage pour les membres et faire quelques M - L - XL de plus?

**Comment by stecaron** [comment]
@jcyelle je t'assigne pour le moment. On pourra réassigner quelqu'un d'autre en temps et lieu pour t'aider ! On se disait que ca serait nice avec des ptits t-shirts .Layer haha

**Comment by stecaron** [comment]
La commande est passé. Le prix : 15$ par t-shirt. Il y en aura quelques uns de plus. Je vais les payer pour le moment et on pourra les redistribuer (vendre) plus tard.
