### ISSUE TITLE
Créer repo charte graphique

### ISSUE THREAD

**Issue by stecaron** [dot-layer/community-tasks#28]
ETA: 25 Janvier 2019

**Comment by stecaron** [comment]
Je pourrai t'aider à créer le repo @jcyelle. Dès que tu auras terminé la charte graphique on pourra mettre ça avec le folder que tu m'as envoyé l'autre et bingo !

**Comment by jcyelle** [comment]
Yes je travaille sur ça!

**Comment by stecaron** [comment]
Done : https://github.com/dot-layer/brand-identity
