### ISSUE TITLE
OSBL set up

### ISSUE THREAD

**Issue by stecaron** [dot-layer/community-tasks#5]
Gather all the necessary information required to create an OSBL. If the option is realistic and well suited, make the arrangements to set up the organisation.

- [x] Gather OSBL informations to be known
- [ ] Make the arrangements to be officially recognized as an OSBL

**Comment by davebulaval** [comment]
Make arrangements :
- Define the objectives
- Define a name for the organization
- Define 3 initial members
- Organization of the CA : President, communication, ...

**Comment by davebulaval** [comment]
Documents : 
[re-101(2018-01).pdf](https://github.com/dot-layer/community-tasks/files/2348949/re-101.2018-01.pdf)
[re-303.g(2017-04).pdf](https://github.com/dot-layer/community-tasks/files/2348950/re-303.g.2017-04.pdf)
[re-303(2017-04)dxi.pdf](https://github.com/dot-layer/community-tasks/files/2348951/re-303.2017-04.dxi.pdf)

**Comment by stecaron** [comment]
J'ai pris rdv pris rdv pour parler au téléphone avec un de mes amis comptables qui connait bien les OSBL et tout. Je vous tiens au courant après mon appel demain.

**Comment by samperochkin** [comment]
@jtbai devrait prendre un rendez-vous avec entrepreneuriat ulaval pour avoir plus de détails. Il va pooler ça avec dans une consultation avec nuSavons (et p-ê autres). C'est quoi les préparatifs dont t'as besoin pour la partie dot-layer?

**Comment by davebulaval** [comment]
@samperochkin Je suis d'accord. Je vais push la modification. 
Je pense qu'on devrais partir la procédure début Octobre pour faire notre premier rencontre pour voter le CA durant la semaine de ML en assurance en Novembre.

**Comment by davebulaval** [comment]
Idée d'objectif :
Regrouper en personne morale toutes les personnes intéressées au développement culturel scientifique, économique et social de la région de Québec et des environs.

Promouvoir le développement culturel scientifique, économique et social de cette région.

**Comment by stecaron** [comment]
J'ai fais la demande de réservation de nom au registre des entreprises. Aussitôt qu'on recoit la confirmation, ne reste plus qu'à envoyer le formulaire. Pour le moment, j'ai mis moi, @davebulaval et @samperochkin comme administrateurs provisoires.

Les prochaines étapes seront:
1. D'élire les administrateurs officiels. 
2. Faire la demande de modification pour updater ces nouveaux admins. 
3. Envoyer une demande de modification pour ajouter un "autre nom" d'utilisation (.layer).
4. Rédiger un document avec les règlements généraux de l'organisme
5. Faire une demande pour [remboursement de la TPS](https://www.canada.ca/content/dam/cra-arc/formspubs/pub/rc4034/rc4034-18f.pdf)
