### ISSUE TITLE
Branding and logo

### ISSUE THREAD

**Issue by stecaron** [dot-layer/community-tasks#6]
Design and first basic and simple logo and branding that will represent the community.

**Comment by stecaron** [comment]
For now, Jean-Christophe Yelle is proposing himself to help for that.

**Comment by stecaron** [comment]
Jee is about to start working on the logo and the branding. He asked us to thing about a slogan we should have. For now, I wrote something on the blog that is more specific for a blog : "Bloggers write. Passionate people share."

@ngarneau @caronl @samperochkin @vincelac @philbl @chblw @jtbai should we define something more general? Do you think we could have a slogan for the community as a whole and slogan for the blog? Do you have any other ideas?

**Comment by jcyelle** [comment]
I think that the slogan have to be general and that words ''machine learning'' must be in the slogan.

We could have a general logo for .layer and variations of it for the blog, the podcast, etc.. and "Bloggers write. Passionate people share." could be part of the variation of the blog logo.. example : 

.layer
Machine Learning Community (or something else...)

blog.layer
Bloggers write. Passionate people share.

podcast.layer
slogan...

**Comment by samperochkin** [comment]
Meet.share.Learn.
