### ISSUE TITLE
Create repo for past and future events

### ISSUE THREAD

**Issue by samperochkin** [dot-layer/community-tasks#7]
@stecaron va créer un repo qui servira (potentiellement) à organiser de nouveaux événements.

Les présentateurs des événements précédents (ie, le chalet) seront invités à déposer leurs slides qqpart. Ça nous permettra de centralisée l'accès aux présentations/slides.

**Comment by stecaron** [comment]
J'ai créé le repo community-events et j'ai créé une section `presentations/`. Si vous voulez structurer le repo autrement je vous laisse la possibilité de changer ça (pour l'instant c'est ce que j'ai pensé).

J'ai mis les deux presentations que moi et @samperochkin on a fait. J'ai mis le code et les slides.

**Comment by stecaron** [comment]
https://github.com/dot-layer/community-events

**Comment by chblw** [comment]
Il semble que les push access sont pas correct sur le repo.

**Comment by stecaron** [comment]
Yep @chblw je suis en train de checker ça live !

**Comment by stecaron** [comment]
@davebulaval est-ce que tu penses que tu peux mettre ta page .md avec tes livres de références? 

@ngarneau tu pourrais aussi y déposer tes slides si y'a pas trop de secrets que tu ne veux pas révéler dedans !

**Comment by davebulaval** [comment]
@stecaron un lien vers le dépôt ou on rajoute un dépôt local dans l'organisation avec le .md ?

**Comment by stecaron** [comment]
@davebulaval tu peux rajouter ton .md juste ici

https://github.com/dot-layer/community-events/tree/master/presentations/2018/chalet

**Comment by davebulaval** [comment]
@stecaron j'arrive pas à push sur le repo. j'ai pas les droits d'écriture.

**Comment by stecaron** [comment]
@davebulaval Done !
