### ISSUE TITLE
OpenLayer podcast

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/community-tasks#8]
Working on the concept of the podcast.
Find a place to record (possibility to the UL central)
Created the Youtube Channel
Patreon ?

**Comment by samperochkin** [comment]
OpenLayer: gros nom. Y'a déjà un channel youtube avec ce nom sauf right?

**Comment by davebulaval** [comment]
@samperochkin Je n'en ai pas trouver.

**Comment by stecaron** [comment]
Pense pas qu'on a besoin d'un issue pour ça. Éventuellement, j'imagine qu'on va avoir un repo ou une manière plus flexible de suivre le développement de ce projet la.
